org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
# Engine Termux ditulis untuk R transitif.
android.nonTransitiveRClass=false
kotlin.code.style=official

# Dibaca oleh build.gradle modul engines/termux
ndkVersion=22.1.7171670
markwonVersion=4.6.2
